In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv('gurgaon_properties.csv')

In [ ]:
df.isnull().sum()

property_name        0
property_type        0
society              0
price               19
price_per_sqft      19
area                19
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom       0
address             11
floorNum            19
facing             303
agePossession        1
nearbyLocations    206
description          0
furnishDetails       0
features           708
rating             449
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2293,3 BHK Flat in Sector 56 Gurgaon,flat,park view apartment,1.74,7565.0,2300.0,Super Built up area 2450(227.61 sq.m.)Built Up...,3,3,3+,"pooja room,servant room","Sector 56, Sector 56 Gurgaon, Gurgaon, Haryana",2.0,South,10+ Year Old,"['Sector 54 chowk metro station', 'Sector metr...",Check out this 3 bhk apartment for sale in par...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2717,1 BHK Flat in Sector 71 Gurgaon,flat,signature andour heights,0.39,9846.0,396.0,Super Built up area 325(30.19 sq.m.),1,1,2,not available,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,Na,0 to 1 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",Signature andour heights is one of the most po...,[],NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1135,3 BHK Flat in Sector 104 Gurgaon,flat,puri emerald bay,2.23,9911.0,2250.0,Super Built up area 2450(227.61 sq.m.)Carpet a...,3,4,3+,servant room,"10th, Sector 104 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...",This beautiful 3 bhk flat in sector 104 gurgao...,"['5 Fan', '1 Exhaust Fan', '16 Light', '5 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
3035,4 Bedroom House for sale in Nirvana Country,house,unitech espace,7.45,34491.0,2160.0,Plot area 240(200.67 sq.m.)Built Up area: 4500...,4,4,3,servant room,"240 Sq.Yds Duplex Villa, Nirvana Country, Gurg...",3.0,NaN,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...","240 sq.Yds old built duplex villa on sale, at ...","['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '15 L...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment5 out of 5', 'Safety5 out of 5', ..."
889,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.75,8882.0,1970.0,Super Built up area 1970(183.02 sq.m.),4,4,1,not available,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12.0,North-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of gurgaon's most sought a...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."

In [ ]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 23A Gurgaon,flat,ashiana apartment,Sector 23A,0.16,2051.0,780.0,Super Built up area 780(72.46 sq.m.),2,2,2,not available,"Sector 23A Gurgaon, Gurgaon, Haryana",1.0,Na,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Residential apartment for sell.Located on 1st ...,[],NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,34 Bedroom House for sale in Manohar Nagar,house,manohar nagar,Manohar Nagar,5.60,12444.0,4500.0,Plot area 500(418.06 sq.m.)Built Up area: 500 ...,34,34,3+,not available,"230/26, Manohar Nagar, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Shiv Mahima Patient Care Bureau', 'Navjeevan...",This is a newly constructed building. With pro...,"['36 Fan', '51 Light', 'No AC', 'No Bed', 'No ...",NaN,NaN
2,1 Bedroom House for sale in Sector 39 Gurgaon,house,independent,Sector 39,1.80,21875.0,823.0,Plot area 900(83.61 sq.m.)Built Up area: 800 s...,1,1,2,not available,"00., Sector 39 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",1bhk residential house for resale in sector 39...,Na,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,4 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,Sector 48,7.35,22812.0,3222.0,Plot area 358(299.33 sq.m.),4,5,2,"servant room,store room,study room,pooja room","001, Sector 48 Gurgaon, Gurgaon, Haryana",2.0,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Tatvam villas is one of the most luxurious res...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '14 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
4,4 BHK Flat in Sector 82 Gurgaon,flat,mapsko casa bella,Sector 82,3.00,6134.0,4891.0,Super Built up area 4890(454.3 sq.m.),4,6,3+,"pooja room,servant room","A1-2501, Sector 82 Gurgaon, Gurgaon, Haryana",25.0,West,1 to 5 Year Old,"['Vatika City Centre Mall', 'Pataudi Road', 'B...",Best location and amazing view from the pentho...,"['1 Water Purifier', '12 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction4 out ..."

In [ ]:
df['sector'] = df['sector'].str.lower()

In [ ]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 63a                                                    18
sector 74                                                     18
sector 78                                                     18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 1 imt manesar                                          14
sector 52                                                     14
sector 3                                                      14
gwal pahari                                                   14
sector 76                                                     14
dlf phase 5                                                   14
sector 53                                                     14
rajendra park                                                 14
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 46                                                     13
uppals southend                                               12
sector 38                                                     12
sohna road                                                    12
sector 50                                                     12
sector 31                                                     12
sector 39                                                     12
ashok vihar phase 3 extension                                 11
sector 93                                                     11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 55                                                      9
south city 1                                                   9
sector 4                                                       9
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
malibu town                                                    8
palam vihar extension                                          8
sector 89 a                                                    8
sector 40                                                      8
sector 43                                                      8
sector 57                                                      8
dwarka expressway                                              8
sector 59                                                      8
sector 10a                                                     8
new colony                                                     7
sector 26                                                      7
sector 11                                                      7
sector 58                                                      7
mianwali colony                                                7
sector 51                                                      7
sector 36 sohna                                                7
surat nagar 1                                                  7
ashok vihar                                                    6
jyoti park                                                     6
sector 5                                                       6
sector 1                                                       6
rajiv nagar                                                    6
jacobpura                                                      6
sector 28                                                      5
greenwood city                                                 5
chakkarpur                                                     5
sector 30                                                      5
sector 23a                                                     5
sector 105                                                     5
manesar                                                        5
new palam vihar                                                5
saraswati vihar                                                5
ansal plaza                                                    5
sector 2                                                       5
sector 80                                                      5
dayanand colony                                                5
sector 9                                                       5
arjun nagar                                                    5
subhash nagar                                                  5
sushant lok phase 2                                            5
sector 6                                                       4
ravi nagar                                                     4
surya vihar                                                    4
shivaji nagar                                                  4
sector 12a                                                     4
sector 3a                                                      4
sector 12                                                      4
devilal colony                                                 4
dharam colony                                                  4
vishnu garden                                                  4
sector 45                                                      4
krishna colony                                                 4
sector 36                                                      4
bhondsi                                                        4
shivpuri                                                       4
sector 17                                                      4
adarsh nagar                                                   4
madanpuri                                                      4
imt manesar                                                    4
suncity                                                        4
new                                                            4
baldev nagar                                                   4
garhi harsaru                                                  4
bhim nagar                                                     4
valley view estate                                             4
sector 17b                                                     3
maruti kunj                                                    3
sector 27                                                      3
sector 15                                                      3
sector 73                                                      3
sector 110 a                                                   3
patel nagar                                                    3
a block sushant lok phase 1                                    3
shakti nagar                                                   3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 8                                                       3
mg road                                                        3
gandhi nagar                                                   3
sector 17a                                                     3
prem nagar                                                     3
sector 88b                                                     3
sector 23                                                      3
bhawani enclave                                                2
block a surya vihar                                            2
hira nagar                                                     2
mayfield garden                                                2
farukhnagar                                                    2
nars                                                           2
faridabad road                                                 2
new basti                                                      2
shanti nagar                                                   2
sector-11 sohna                                                2
iffco chowk                                                    2
sheetla colony                                                 2
golf course road                                               2
sector 32                                                      2
bissar                                                         2
acharya puri                                                   2
sector 15 part 2                                               2
sector 41                                                      2
rajiv chowk                                                    2
new palam vihar phase 1                                        2
, delhi ncr                                                    2
rosewood                                                       2
sector 24                                                      2
sector-2 sohna                                                 2
manohar nagar                                                  2
ambience island                                                2
mohan nagar                                                    2
sector 15 part 1                                               2
sohna  road                                                    2
west rajiv nagar                                               2
sispal vihar                                                   2
pratap nagar                                                   2
sector 21                                                      2
surat nagar phase 2                                            2
daulatabad                                                     2
sushant lok                                                    2
shankar vihar                                                  2
samaspur                                                       2
lajpat nagar                                                   2
surat nagar                                                    2
golf course ext road                                           2
new palam vihar phase 2                                        2
sadar bazar                                                    1
sector-5 sheetla colony                                        1
sector 9b                                                      1
ats marigold                                                   1
v block dlf phase 3                                            1
laxmna vihar, phase 2                                          1
sector-35 sohna                                                1
hsiidc plot sector 1 imt manesar                               1
mahavir pura                                                   1
anand garden, sector-105                                       1
garauli kalan                                                  1
sector 42                                                      1
sector 4 urban estate                                          1
sector 37a                                                     1
ashok vihar phase i                                            1
alipur                                                         1
sector 17c                                                     1
sultanpur                                                      1
vir nagar                                                      1
ravi nager basai road                                          1
near euro                                                      1
kheri                                                          1
jat colony,fazilpur/taj nagar road                             1
sector 21a faridabad                                           1
carterpuri village                                             1
cyber city                                                     1
near sector 1 market                                           1
begampur khatola                                               1
mahalaxmi garden, rajendra place                               1
block h ashok vihar phase iii extension                        1
sector 13                                                      1
hno 13 sagar enclave sura                                      1
godrej aria , sector 79 ,                                      1
laxman vihar, railway road,                                    1
dhankot                                                        1
sector 37b                                                     1
damdma                                                         1
shivji park colony                                             1
huda saraswati vihar                                           1
saraswati enclave                                              1
pataudi road                                                   1
kanahi                                                         1
g block dlf city phase 1                                       1
naharpur rupa                                                  1
udyog vihar phase 1                                            1
near pataudi chowk                                             1
bhimgarh kheri phase 3                                         1
saroop garden rajendra park                                    1
heritage city                                                  1
park view                                                      1
rajiv colony                                                   1
tekchand nagar                                                 1
gopal nagar, garhi ghasita, sonipat                            1
sector 5 chowk                                                 1
urban estate, sector 5                                         1
lucknow                                                        1
new colony, sector 7                                           1
near khandsa road                                              1
nirvana country pocket h                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
bhora kalan                                                    1
new jyoti park                                                 1
bptp                                                           1
b1 block sector 57                                             1
near nand hospital                                             1
om nagar                                                       1
sai kunj                                                       1
jacobpura near sadar bazar                                     1
ansal's palam vihar                                            1
block g sector-57                                              1
ram nagar                                                      1
rattan garden                                                  1
ashok vihar phase 3                                            1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector-5 sohna                                                 1
civil l                                                        1
khandsa                                                        1
old delhi road, opp sector-14                                  1
south city                                                     1
part 3 sector 5                                                1
sector-7 hous                                                  1
Name: sector, dtype: int64

In [ ]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [ ]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [ ]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [ ]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [ ]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [ ]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [ ]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [ ]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [ ]:
df['sector'].value_counts()

sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 24                      24
sector 105                     23
sector 33                      23
sector 88a                     23
sector 14                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 82a                     20
sector 3                       20
sector 22                      20
sector 47                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 78                      18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 1 manesar               14
sector 52                      14
sector 53                      14
sector 55                      14
sector 76                      14
sector 46                      13
sector 9                       13
sector 6                       13
sector 4 phase 2               13
sector 36a                     13
sohna road road                12
sector 38                      12
sector 31                      12
sector 39                      12
sector 9a                      11
sector 3 phase 3 extension     11
sector 93                      11
sector 41                      11
sector 1a manesar              10
sector 13                      10
sector 95a                      9
sector 45                       9
manesar                         9
sector 3 phase 2                9
sector 89 a                     8
sector 2 extension              8
c block sector 43               8
sector 40                       8
sector 59                       8
sector 10a                      8
dwarka expressway               8
sector 23                       8
sector 17                       8
sector 8                        8
sector 58                       7
sector 51                       7
sector 36 sohna road            7
sector 1                        6
sector 5                        6
sector 21                       6
sector 23a                      5
sector 30                       5
sector 80                       5
new sector 2                    5
sector 3a                       4
new                             4
sector 12a                      4
sector 36                       4
sector 110 a                    3
b block sector 43               3
sector 17a                      3
patel nagar                     3
sector 88b                      3
sector 15                       3
sector 27                       3
sector 17b                      3
maruti kunj                     3
sector 73                       3
a block sector 43               3
Name: sector, dtype: int64

In [ ]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [ ]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [ ]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
236,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,Na,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
888,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,Na,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1764,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,Na,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2107,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,Na,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [ ]:
df.loc[22,'sector'] = 'sector 90'
df.loc[888,'sector'] = 'sector 92'
df.loc[1764,'sector'] = 'sector 37'
df.loc[2107,'sector'] = 'sector 76'

In [ ]:
df[df['sector'] == 'new sector 2']

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
6,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Na,NaN
247,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,1.0,Na,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN
1391,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,1.0,Na,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Na,NaN
2987,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']"
3439,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,2.0,Na,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']"

In [ ]:
df.loc[[6,247,1391,2987,3439],'sector'] = 'sector 110'

In [ ]:
df.shape

(3801, 17)

In [ ]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

KeyError: "['property_name', 'address', 'description', 'rating'] not found in axis"

In [ ]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
271,flat,ramprastha the edge towers,sector 37d,1.10,5528.0,1990.0,Built Up area: 1990 (184.88 sq.m.),3,3,3,not available,9.0,Na,undefined,"['MDS Public School', 'St Pauls School', 'Sunc...",Na,NaN
3928,flat,conscient heritage max,sector 102,1.75,9011.0,1942.0,Super Built up area 1942(180.42 sq.m.),3,4,3+,servant room,13.0,North,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...","['2 Wardrobe', '4 Fan', '2 Geyser', '1 Stove',...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
15,flat,dlf garden city floors,sector 92,1.70,8588.0,1980.0,Super Built up area 1630(151.43 sq.m.),3,4,2,not available,1.0,Na,Dec 2024,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",[],NaN
569,flat,bptp terra,sector 37d,1.50,8255.0,1817.0,Super Built up area 1811(168.25 sq.m.)Carpet a...,3,3,3,others,12.0,South-West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","['1 Wardrobe', '1 Modular Kitchen', '3 AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
975,house,independent,sector 91,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),4,4,3,not available,2.0,North-East,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","['4 Wardrobe', '9 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."

In [ ]:
df.duplicated().sum()

122

In [ ]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)